"""project invites and members tables

Revision ID: 3e1cf0c4b98c
Revises: b96f1612eb4a
Create Date: 2026-05-14 05:01:29.815995

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e1cf0c4b98c"
down_revision: str | Sequence[str] | None = "b96f1612eb4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("send_by", sa.Integer(), nullable=False),
        sa.Column("send_to", sa.Integer(), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum("viewer", "worker", "admin", name="project_invite_access_level"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "declined",
                "revoked",
                name="project_invite_status",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["send_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["send_to"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("VIEWER", "WORKER", "ADMIN", name="projectinviteaccesslevel"),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "user_id", name="uq_project_members_project_id_user_id"
        ),
    )
    op.drop_constraint(op.f("sprints_project_id_fkey"), "sprints", type_="foreignkey")
    op.create_foreign_key(
        None, "sprints", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sprints", type_="foreignkey")
    op.create_foreign_key(
        op.f("sprints_project_id_fkey"), "sprints", "projects", ["project_id"], ["id"]
    )
    op.drop_table("project_members")
    op.drop_table("project_invites")
    # ### end Alembic commands ###
