"""hardening indexes and constraints

Revision ID: 83d8f1492cb8
Revises: c0ed6a549686
Create Date: 2026-07-18 11:23:16.116797

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83d8f1492cb8"
down_revision: str | Sequence[str] | None = "c0ed6a549686"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_projects_name_min_length",
        "projects",
        "length(name) >= 3",
    )
    op.create_index("ix_projects_owner_id", "projects", ["owner_id"], unique=False)
    op.create_index(
        "ix_project_invites_pending_project_send_to",
        "project_invites",
        ["project_id", "send_to"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
        sqlite_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_project_invites_send_to_status",
        "project_invites",
        ["send_to", "status"],
        unique=False,
    )
    op.create_index(
        "ix_refresh_sessions_expires_at",
        "refresh_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_refresh_sessions_user_id",
        "refresh_sessions",
        ["user_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("refresh_sessions_user_id_fkey"),
        "refresh_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_refresh_sessions_user_id_users",
        "refresh_sessions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_check_constraint(
        "ck_sprints_active_has_starts_at",
        "sprints",
        "status != 'active' OR starts_at IS NOT NULL",
    )
    op.create_check_constraint(
        "ck_sprints_closed_has_closed_at",
        "sprints",
        "status != 'closed' OR closed_at IS NOT NULL",
    )
    op.create_index(
        "ix_sprints_lifecycle",
        "sprints",
        ["status", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_index(
        "ix_sprints_project_status",
        "sprints",
        ["project_id", "status"],
        unique=False,
    )
    op.create_check_constraint(
        "ck_tasks_title_min_length",
        "tasks",
        "length(title) >= 3",
    )
    op.create_index(
        "ix_tasks_project_sprint_status",
        "tasks",
        ["project_id", "sprint_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_tasks_project_sprint_worker",
        "tasks",
        ["project_id", "sprint_id", "worker_id"],
        unique=False,
    )
    op.create_index(
        "ix_tasks_worker_status",
        "tasks",
        ["worker_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_tasks_project_worker_status",
        "tasks",
        ["project_id", "worker_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_worker_status", table_name="tasks")
    op.drop_index("ix_tasks_project_worker_status", table_name="tasks")
    op.drop_index("ix_tasks_project_sprint_worker", table_name="tasks")
    op.drop_index("ix_tasks_project_sprint_status", table_name="tasks")
    op.drop_constraint("ck_tasks_title_min_length", "tasks", type_="check")
    op.drop_index("ix_sprints_project_status", table_name="sprints")
    op.drop_index("ix_sprints_lifecycle", table_name="sprints")
    op.drop_constraint("ck_sprints_closed_has_closed_at", "sprints", type_="check")
    op.drop_constraint("ck_sprints_active_has_starts_at", "sprints", type_="check")
    op.drop_constraint(
        "fk_refresh_sessions_user_id_users",
        "refresh_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("refresh_sessions_user_id_fkey"),
        "refresh_sessions",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_index("ix_refresh_sessions_user_id", table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_expires_at", table_name="refresh_sessions")
    op.drop_index("ix_project_invites_send_to_status", table_name="project_invites")
    op.drop_index(
        "ix_project_invites_pending_project_send_to",
        table_name="project_invites",
        postgresql_where=sa.text("status = 'pending'"),
        sqlite_where=sa.text("status = 'pending'"),
    )
    op.drop_index("ix_projects_owner_id", table_name="projects")
    op.drop_constraint("ck_projects_name_min_length", "projects", type_="check")
    # ### end Alembic commands ###
