"""new logic

Revision ID: c0ed6a549686
Revises: 176f6f24bccb
Create Date: 2026-06-24 19:26:40.767020

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0ed6a549686"
down_revision: str | Sequence[str] | None = "176f6f24bccb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("project_invites_project_id_fkey"), "project_invites", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("project_invites_send_by_fkey"), "project_invites", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("project_invites_send_to_fkey"), "project_invites", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "project_invites", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "project_invites", "users", ["send_by"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "project_invites", "users", ["send_to"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("project_members_user_id_fkey"), "project_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "project_members", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("projects_owner_id_fkey"), "projects", type_="foreignkey")
    op.create_foreign_key(
        None, "projects", "users", ["owner_id"], ["id"], ondelete="RESTRICT"
    )
    op.alter_column(
        "review_comments", "author_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("review_comments_author_id_fkey"), "review_comments", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "review_comments", "users", ["author_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column("sprints", "creator_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("sprints_creator_id_fkey"), "sprints", type_="foreignkey")
    op.create_foreign_key(
        None, "sprints", "users", ["creator_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column("tasks", "creator_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("tasks_worker_id_fkey"), "tasks", type_="foreignkey")
    op.drop_constraint(op.f("tasks_creator_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["worker_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "tasks", "users", ["creator_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_creator_id_fkey"), "tasks", "users", ["creator_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("tasks_worker_id_fkey"), "tasks", "users", ["worker_id"], ["id"]
    )
    op.alter_column("tasks", "creator_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(None, "sprints", type_="foreignkey")
    op.create_foreign_key(
        op.f("sprints_creator_id_fkey"), "sprints", "users", ["creator_id"], ["id"]
    )
    op.alter_column("sprints", "creator_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(None, "review_comments", type_="foreignkey")
    op.create_foreign_key(
        op.f("review_comments_author_id_fkey"),
        "review_comments",
        "users",
        ["author_id"],
        ["id"],
    )
    op.alter_column(
        "review_comments", "author_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.create_foreign_key(
        op.f("projects_owner_id_fkey"), "projects", "users", ["owner_id"], ["id"]
    )
    op.drop_constraint(None, "project_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("project_members_user_id_fkey"),
        "project_members",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "project_invites", type_="foreignkey")
    op.drop_constraint(None, "project_invites", type_="foreignkey")
    op.drop_constraint(None, "project_invites", type_="foreignkey")
    op.create_foreign_key(
        op.f("project_invites_send_to_fkey"),
        "project_invites",
        "users",
        ["send_to"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("project_invites_send_by_fkey"),
        "project_invites",
        "users",
        ["send_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("project_invites_project_id_fkey"),
        "project_invites",
        "projects",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
