"""upgraded tables - enum fixed

Revision ID: c7353595abfd
Revises: 3e1cf0c4b98c
Create Date: 2026-05-17 04:35:00.140311

"""

from collections.abc import Sequence

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7353595abfd"
down_revision: str | Sequence[str] | None = "3e1cf0c4b98c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    new_enum = postgresql.ENUM("viewer", "worker", "admin", name="project_member_role")
    new_enum.create(op.get_bind(), checkfirst=True)

    op.execute(
        "ALTER TABLE project_members ALTER COLUMN role TYPE project_member_role "
        "USING LOWER(role::text)::project_member_role"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    old_enum = postgresql.ENUM(
        "VIEWER", "WORKER", "ADMIN", name="projectinviteaccesslevel"
    )
    old_enum.create(op.get_bind(), checkfirst=True)

    op.execute(
        "ALTER TABLE project_members ALTER COLUMN role TYPE projectinviteaccesslevel "
        "USING UPPER(role::text)::projectinviteaccesslevel"
    )

    new_enum = postgresql.ENUM("viewer", "worker", "admin", name="project_member_role")
    new_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
